# Provide MySQL with phpMyAdmin
version: '3.3'

services:
  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      - PMA_HOST=mysql
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=default
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']